# numpy 50 functions

In [1]:
import numpy as np

In [2]:
a=np.zeros(4)

In [3]:
a


array([0., 0., 0., 0.])

In [4]:
type(a)

numpy.ndarray

In [5]:
type(a[2])

numpy.float64

In [6]:
c=np.ones(5)

In [7]:
c

array([1., 1., 1., 1., 1.])

In [9]:
d=np.empty(10)

In [10]:
d

array([9.81401551e-312, 2.17388884e-322, 0.00000000e+000, 0.00000000e+000,
       1.00238459e-044, 1.16095484e-028, 9.34634030e+218, 4.25757502e-096,
       9.78750380e+199, 6.97843734e+252])

In [11]:
c.dtype

dtype('float64')

In [16]:
d.shape =(5,2)
d

array([[9.81401551e-312, 2.17388884e-322],
       [0.00000000e+000, 0.00000000e+000],
       [1.00238459e-044, 1.16095484e-028],
       [9.34634030e+218, 4.25757502e-096],
       [9.78750380e+199, 6.97843734e+252]])

In [19]:
e=np.linspace(3,20,5)
e

array([ 3.  ,  7.25, 11.5 , 15.75, 20.  ])

In [20]:
f=np.arange(3,30,5)
f

array([ 3,  8, 13, 18, 23, 28])

In [21]:
list=[[1,2,3,4],[6,7,8,9]]
g=np.array([list])
g

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]]])

In [23]:
g.shape

(1, 2, 4)

In [ ]:
# mathimatical functions

In [25]:
h=np.random.randint(50,size=20)
h

array([38, 32, 34, 32, 17,  7, 33, 15, 46, 25, 18, 36, 24, 44, 29, 41, 32,
       40, 21,  3])

In [26]:
h[0]

38

In [27]:
h[0:6]

array([38, 32, 34, 32, 17,  7])

In [28]:
h[-3]

40

In [29]:
h>30

array([ True,  True,  True,  True, False, False,  True, False,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
       False, False])

In [30]:
h[h>20]

array([38, 32, 34, 32, 33, 46, 25, 36, 24, 44, 29, 41, 32, 40, 21])

In [31]:
h*2

array([76, 64, 68, 64, 34, 14, 66, 30, 92, 50, 36, 72, 48, 88, 58, 82, 64,
       80, 42,  6])

In [32]:
h/2

array([19. , 16. , 17. , 16. ,  8.5,  3.5, 16.5,  7.5, 23. , 12.5,  9. ,
       18. , 12. , 22. , 14.5, 20.5, 16. , 20. , 10.5,  1.5])

In [33]:
h-10

array([28, 22, 24, 22,  7, -3, 23,  5, 36, 15,  8, 26, 14, 34, 19, 31, 22,
       30, 11, -7])

In [34]:
z=np.array([1,2,3,4,5,6,7,8,9,10])
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
z.mean()

5.5

z.cumsum()

In [37]:
z.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [38]:
z.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [39]:
z.sum

<function ndarray.sum>

In [40]:
y=z<5

In [41]:
y

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [42]:
z.any()

True

In [43]:
y.all()

False

In [44]:
s=np.array([3,5,7,2,20,23,40,77,66,33,])
s

array([ 3,  5,  7,  2, 20, 23, 40, 77, 66, 33])

In [47]:
s.sort()
s

array([ 2,  3,  5,  7, 20, 23, 33, 40, 66, 77])

In [49]:
n=[1,1,1,2,2,2,3,3,4,4,45,5,5,]
n


[1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 45, 5, 5]

In [50]:
np.unique(n)

array([ 1,  2,  3,  4,  5, 45])

# save function

In [53]:
A1=["malik","hamza","aslam","from","kashmir"]
A2=["student","of","PIAIC","and","electronics","engineer"]


In [54]:
A1

['malik', 'hamza', 'aslam', 'from', 'kashmir']

In [55]:
A2

['student', 'of', 'PIAIC', 'and', 'electronics', 'engineer']

In [56]:
import numpy as np

In [62]:
np.save("name.npy",A1)

In [63]:
L1=np.load ("name.npy")

In [64]:
L1

array(['malik', 'hamza', 'aslam', 'from', 'kashmir'], dtype='<U7')